name: Laravel Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      #      - name: Build and push docker
      #        uses: docker/build-push-action@v5.1.0
      #        with:
      #          username: ${{ secrets.REGISTRY_USERNAME }}
      #          password: ${{ secrets.REGISTRY_PASSWORD }}
      #          repository: DOCKER_REPOSITORY
      #          tags: latest
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Branch
        id: branch
        run: echo "git_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_BRANCH

      - name: Check Branch
        run: echo "${{ env.branch }}"

      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

      - name: Check Hash
        run: echo "${{ env.hash }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          tags: hendisantika/laravel-upload-photo:latest

