name: Laravel Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      #      - name: Build and push docker
      #        uses: docker/build-push-action@v5.1.0
      #        with:
      #          username: ${{ secrets.REGISTRY_USERNAME }}
      #          password: ${{ secrets.REGISTRY_PASSWORD }}
      #          repository: DOCKER_REPOSITORY
      #          tags: latest
      #
      - name: Get Git Short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${{ github.sha }} | cut -c1-7)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true

          repository: hendisantika/laravel-upload-photo
          tag_with_sha: true
#          tags: hendisantika/laravel-upload-photo:latest


