name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Get repository release tag
        id: timeseries
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          excludes: prerelease, draft
          repository: ${{ github.repository }}

      - name: Build Docker image
        run: |
          docker build --network=host -t ${{secrets.DOCKER_USER}}/MY_REPO:latest -t ${{secrets.DOCKER_USER}}/MY_REPO:${{ steps.timeseries.outputs.release }} .

      - name: Docker push image
        run: |
          docker push ${{secrets.DOCKER_USER}}/laravel-upload-photo
          docker push ${{secrets.DOCKER_USER}}/laravel-upload-photo:${{ steps.timeseries.outputs.release }}
